build-jar-new:
  image: "openjdk:8-jdk"
  stage: build-jar
  only:
    changes:
      - "*"  # run pipeline if a root-level file like Makefile or docker-compose.yml is changed
      - "new/**/*"
  before_script:
    - cd new
    - chmod +x gradlew
  script:
    - ./gradlew bootJar

build-image-new:
  stage: build-image
  script:
    - docker build -t asia.gcr.io/pegipegi-user/cicd/new .
  needs:
    - build-jar-new
