build-jar-new:
  image: "openjdk:8-jdk"
  stage: build-jar
  only:
    changes:
      - "*"  # run pipeline if a root-level file like Makefile or docker-compose.yml is changed
      - "new/**/*"
  before_script:
    - cd new
    - chmod +x gradlew
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - new/build/libs/

build-image-new:
  image: docker:latest
  services:
    - docker:dind
  stage: build-image
  only:
    changes:
      - "*"  # run pipeline if a root-level file like Makefile or docker-compose.yml is changed
      - "new/**/*"
  before_script:
    - cd new
  script:
    - docker build -t asia.gcr.io/pegipegi-user/cicd/new .
  needs:
    - build-jar-new
