build-jar-complete:
  image: "openjdk:8-jdk"
  stage: build-jar
  only:
    changes:
      - "*"  # run pipeline if a root-level file like Makefile or docker-compose.yml is changed
      - "complete/**/*"
  script:
    - chmod +x complete/gradlew
    - complete/gradlew clean bootJar

# build-image-complete:
#   stage: build-image
#   script:
#     - docker build -t test .
#   needs:
#     - build-jar-complete
