build-jar-complete:
  image: "openjdk:8-jdk"
  stage: build-jar
  only:
    changes:
      - "*"  # run pipeline if a root-level file like Makefile or docker-compose.yml is changed
      - "complete/**/*"
  before_script:
    - cd complete
    - chmod +x gradlew
  script:
    - ./gradlew bootJar

build-image-complete:
  image: docker:latest
  services:
    - docker:dind
  stage: build-image
  before_script:
    - cd complete
  script:
    - docker build -t asia.gcr.io/pegipegi-user/cicd/complete .
  needs:
    - build-jar-complete
